"use client"

import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer"

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: "Helvetica" },
  title: { fontSize: 16, marginBottom: 20, textAlign: "center" },
  header: { flexDirection: "row", justifyContent: "space-between", marginBottom: 20 },
  headerBlock: { fontSize: 9, width: "30%" },
  label: { fontSize: 8, color: "#666", marginBottom: 2 },
  table: { marginTop: 10 },
  tableHeader: { flexDirection: "row", backgroundColor: "#f5f5f5", borderBottomWidth: 1, borderBottomColor: "#ddd" },
  tableRow: { flexDirection: "row", borderBottomWidth: 0.5, borderBottomColor: "#eee" },
  col1: { width: "5%", padding: 4 },
  col2: { width: "30%", padding: 4 },
  col3: { width: "15%", padding: 4 },
  col4: { width: "15%", padding: 4 },
  col5: { width: "15%", padding: 4 },
  col6: { width: "20%", padding: 4 },
  total: { flexDirection: "row", justifyContent: "flex-end", marginTop: 10, fontSize: 11 },
  footer: { marginTop: 20, fontSize: 8, color: "#999" },
})

interface CommercialInvoiceData {
  seller: { name: string; address: string }
  buyer: { name: string; address: string }
  invoiceNo: string
  date: string
  terms: string
  currency: string
  items: { no: number; description: string; qty: number; unitPrice: number; amount: number }[]
}

export function CommercialInvoicePDF({ data }: { data: CommercialInvoiceData }) {
  const totalAmount = data.items.reduce((s, i) => s + i.amount, 0)

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>COMMERCIAL INVOICE</Text>
        <View style={styles.header}>
          <View style={styles.headerBlock}>
            <Text style={styles.label}>Seller</Text>
            <Text>{data.seller.name}</Text>
            <Text>{data.seller.address}</Text>
          </View>
          <View style={styles.headerBlock}>
            <Text style={styles.label}>Buyer</Text>
            <Text>{data.buyer.name}</Text>
            <Text>{data.buyer.address}</Text>
          </View>
          <View style={styles.headerBlock}>
            <Text style={styles.label}>Invoice No.</Text>
            <Text>{data.invoiceNo}</Text>
            <Text style={styles.label}>Date</Text>
            <Text>{data.date}</Text>
            <Text style={styles.label}>Terms</Text>
            <Text>{data.terms}</Text>
          </View>
        </View>
        <View style={styles.table}>
          <View style={styles.tableHeader}>
            <Text style={styles.col1}>No.</Text>
            <Text style={styles.col2}>Description</Text>
            <Text style={styles.col3}>Qty</Text>
            <Text style={styles.col4}>Unit Price</Text>
            <Text style={styles.col5}>Amount</Text>
            <Text style={styles.col6}>Currency</Text>
          </View>
          {data.items.map((item) => (
            <View key={item.no} style={styles.tableRow}>
              <Text style={styles.col1}>{item.no}</Text>
              <Text style={styles.col2}>{item.description}</Text>
              <Text style={styles.col3}>{item.qty}</Text>
              <Text style={styles.col4}>{item.unitPrice.toFixed(2)}</Text>
              <Text style={styles.col5}>{item.amount.toFixed(2)}</Text>
              <Text style={styles.col6}>{data.currency}</Text>
            </View>
          ))}
        </View>
        <Text style={styles.total}>Total: {data.currency} {totalAmount.toFixed(2)}</Text>
        <Text style={styles.footer}>Generated by Logistics Portal</Text>
      </Page>
    </Document>
  )
}
