"use client"

import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer"

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: "Helvetica" },
  title: { fontSize: 16, marginBottom: 20, textAlign: "center" },
  header: { flexDirection: "row", justifyContent: "space-between", marginBottom: 20 },
  headerBlock: { fontSize: 9, width: "30%" },
  label: { fontSize: 8, color: "#666", marginBottom: 2 },
  table: { marginTop: 10 },
  tableHeader: { flexDirection: "row", backgroundColor: "#f5f5f5", borderBottomWidth: 1, borderBottomColor: "#ddd" },
  tableRow: { flexDirection: "row", borderBottomWidth: 0.5, borderBottomColor: "#eee" },
  col1: { width: "8%", padding: 4 },
  col2: { width: "25%", padding: 4 },
  col3: { width: "12%", padding: 4 },
  col4: { width: "12%", padding: 4 },
  col5: { width: "12%", padding: 4 },
  col6: { width: "12%", padding: 4 },
  col7: { width: "10%", padding: 4 },
  col8: { width: "9%", padding: 4 },
  footer: { marginTop: 20, fontSize: 8, color: "#999" },
})

interface PackingListData {
  shipper: { name: string; address: string; contact: string }
  consignee: { name: string; address: string; contact: string }
  invoiceNo: string
  date: string
  items: { cartonNo: number; description: string; qty: number; gw: number; nw: number; length: number; width: number; height: number }[]
}

export function PackingListPDF({ data }: { data: PackingListData }) {
  const totalQty = data.items.reduce((s, i) => s + i.qty, 0)
  const totalGW = data.items.reduce((s, i) => s + i.gw, 0)
  const totalNW = data.items.reduce((s, i) => s + i.nw, 0)

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>PACKING LIST</Text>
        <View style={styles.header}>
          <View style={styles.headerBlock}>
            <Text style={styles.label}>Shipper / Exporter</Text>
            <Text>{data.shipper.name}</Text>
            <Text>{data.shipper.address}</Text>
            <Text>{data.shipper.contact}</Text>
          </View>
          <View style={styles.headerBlock}>
            <Text style={styles.label}>Consignee</Text>
            <Text>{data.consignee.name}</Text>
            <Text>{data.consignee.address}</Text>
            <Text>{data.consignee.contact}</Text>
          </View>
          <View style={styles.headerBlock}>
            <Text style={styles.label}>Invoice No.</Text>
            <Text>{data.invoiceNo}</Text>
            <Text style={styles.label}>Date</Text>
            <Text>{data.date}</Text>
          </View>
        </View>
        <View style={styles.table}>
          <View style={styles.tableHeader}>
            <Text style={styles.col1}>CTN</Text>
            <Text style={styles.col2}>Description</Text>
            <Text style={styles.col3}>Qty</Text>
            <Text style={styles.col4}>G.W.(kg)</Text>
            <Text style={styles.col5}>N.W.(kg)</Text>
            <Text style={styles.col6}>L(cm)</Text>
            <Text style={styles.col7}>W(cm)</Text>
            <Text style={styles.col8}>H(cm)</Text>
          </View>
          {data.items.map((item) => (
            <View key={item.cartonNo} style={styles.tableRow}>
              <Text style={styles.col1}>{item.cartonNo}</Text>
              <Text style={styles.col2}>{item.description}</Text>
              <Text style={styles.col3}>{item.qty}</Text>
              <Text style={styles.col4}>{item.gw}</Text>
              <Text style={styles.col5}>{item.nw}</Text>
              <Text style={styles.col6}>{item.length}</Text>
              <Text style={styles.col7}>{item.width}</Text>
              <Text style={styles.col8}>{item.height}</Text>
            </View>
          ))}
        </View>
        <View style={{ flexDirection: "row", marginTop: 10, fontSize: 10 }}>
          <Text style={{ width: "33%" }}>Total Qty: {totalQty}</Text>
          <Text style={{ width: "33%" }}>Total G.W.: {totalGW.toFixed(1)} kg</Text>
          <Text style={{ width: "33%" }}>Total N.W.: {totalNW.toFixed(1)} kg</Text>
        </View>
        <Text style={styles.footer}>Generated by Logistics Portal</Text>
      </Page>
    </Document>
  )
}
